# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_salary_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 364)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.firstNameLabel = QtWidgets.QLabel(Dialog)
        self.firstNameLabel.setObjectName("firstNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.firstNameLabel)
        self.lblFirstName = QtWidgets.QLabel(Dialog)
        self.lblFirstName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFirstName.setObjectName("lblFirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblFirstName)
        self.lastNameLabel = QtWidgets.QLabel(Dialog)
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
        self.lblLastName = QtWidgets.QLabel(Dialog)
        self.lblLastName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLastName.setObjectName("lblLastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblLastName)
        self.currentSalaryLabel = QtWidgets.QLabel(Dialog)
        self.currentSalaryLabel.setObjectName("currentSalaryLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.currentSalaryLabel)
        self.lblCurrentSalary = QtWidgets.QLabel(Dialog)
        self.lblCurrentSalary.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCurrentSalary.setObjectName("lblCurrentSalary")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblCurrentSalary)
        self.newSalaryLabel = QtWidgets.QLabel(Dialog)
        self.newSalaryLabel.setObjectName("newSalaryLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.newSalaryLabel)
        self.lineEditNewSalary = QtWidgets.QLineEdit(Dialog)
        self.lineEditNewSalary.setObjectName("lineEditNewSalary")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditNewSalary)
        self.reasonLabel = QtWidgets.QLabel(Dialog)
        self.reasonLabel.setObjectName("reasonLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.reasonLabel)
        self.lineEditReason = QtWidgets.QLineEdit(Dialog)
        self.lineEditReason.setObjectName("lineEditReason")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditReason)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.firstNameLabel.setText(_translate("Dialog", "First Name"))
        self.lblFirstName.setText(_translate("Dialog", "Peter"))
        self.lastNameLabel.setText(_translate("Dialog", "Last Name"))
        self.lblLastName.setText(_translate("Dialog", "Tan"))
        self.currentSalaryLabel.setText(_translate("Dialog", "Current Salary"))
        self.lblCurrentSalary.setText(_translate("Dialog", "20000"))
        self.newSalaryLabel.setText(_translate("Dialog", "New Salary"))
        self.reasonLabel.setText(_translate("Dialog", "Reason"))
        self.lineEditReason.setPlaceholderText(_translate("Dialog", "Optional"))
        self.saveButton.setText(_translate("Dialog", "Save"))
